# 站点信息
title: 杨波波的博客
description: 这是一个关于技术与生活的博客，记录我对知识的总结和对生活的感悟。
url: https://www.ccici.cc
rss_url: /pages/atom.xml

timezone: PRC
encoding: UTF-8

permalink: /:year/:month/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author:
  name: boker
  email: 8236138@qq.com
  link: https://www.ccici.cc
  github: http://github.com/angusty
  # music:
  #linkedin:


# gavatar头像及Favicon
#gavatar: http://7u2mh0.com1.z0.glb.clouddn.com/yboker-me-and-wife-bipenggou.JPG?imageView/2/w/80/h/80
gavatar: /public/img/deer3.png
favicon: http://7u2mh0.com1.z0.glb.clouddn.com/yboker-shooter-arrow.jpg?imageView/2/w/16/h/16

# google analytics 设置
ga:
  id: UA-58266340-1
  url: angusty.com
# baidu analytics
baidu:
  id: 60050c5fbf19983f8b47bf26e240e932

# disqus 设置
disqus:
  shortname: yboker

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates:
  - PHP
  - MySQL
  - JavaScript

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
