# 站点信息
title: yboker的博客
description: yboker的博客,php,web开发
url: http://angusty.com
rss_url: /pages/atom.xml

timezone: PRC
encoding: UTF-8

permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author:
  name: yboker
  email: 8236138@qq.com
  link: http://angusty.com
  weibo: http://weibo.com/u/1348575875
  github: http://github.com/angusty


# gavatar头像及Favicon
gavatar: https://avatars3.githubusercontent.com/u/10364880?v=3&s=460
favicon: https://avatars3.githubusercontent.com/u/10364880?v=3&s=460

# google analytics 设置
ga:
  id: UA-58266340-1
  url: angusty.com
# baidu analytics
baidu:
  id: 60050c5fbf19983f8b47bf26e240e932

# disqus 设置
disqus:
  shortname: yboker

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates:
  - PHP
  - MySQL
  - JavaScript

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录

